import React, {useState} from 'react';
import './App.css'
import upload_img from './assets/preview.jpg'

function App() {
	const [selectedFile, setSelectedFile] = useState();
	const [isFilePicked, setIsFilePicked] = useState(false);
  const [img, setImg] = useState(upload_img)

	const changeHandler = (event) => {
		setSelectedFile(event.target.files[0]);
		setIsFilePicked(true);
    setImg(URL.createObjectURL(event.target.files[0]));
	};

	const handleSubmission = () => {
		const formData = new FormData();

		formData.append('file', selectedFile);

		fetch(
			'https://freeimage.host/api/1/upload?key=<YOUR_API_KEY>',
			{
				method: 'POST',
				body: formData,
			}
		)
			.then((response) => response.json())
			.then((result) => {
				console.log('Success:', result);
			})
			.catch((error) => {
				console.error('Error:', error);
			});
	};

  return (
  <>
    <div className="navbar">
      <div className="left">Image Caption Generator</div>  
      <div className="right">
        <div className='creator'>Creators:</div>
        <div className='names'>
          <div>Riya</div>
          <div>Vanisha</div>
          <div>Vidhi</div>
        </div>
      </div>  
    </div>
    <div className="main">
    <div className="file-selector">
    <label className='custom-upload'>
			<input type="file" name="file" accept="image/*" onChange={changeHandler} className="choose"/>
      Choose Picture
    </label>
			{isFilePicked ? (
				<div className='note'>
					File Selected, Press Upload
				</div>
			) : (
				<p>Select a file to show details</p>
			)}
			<div>
				<button onClick={handleSubmission} className="upload">Upload</button>
			</div>
		</div>
      <img src={img} alt="img" width='200px' height='200px'/>
    </div>
    <div className='results'>
        <div className='head'>
          Caption generated by the model:
        </div>
        <div className='answer'>
          The dog is running behind the girl.
        </div>
    </div>
    <div className="footer">
      Created by IIT Bhilai students, all rights reserved &copy; Copyright 2022
    </div>
  </>
  );
}

export default App;
